import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WorkflowProvider from "./context/WorkflowProvider";
import React from "react";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "./context/theme-provider"; // Ensure this path is correct

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NoCode_ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /* 1. Added suppressHydrationWarning here */
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <React.StrictMode>
          {/* 2. Wrap everything in ThemeProvider */}
          <ThemeProvider
            attribute="class" 
            enableSystem={true}
            defaultTheme="system"
            disableTransitionOnChange
          >
            <WorkflowProvider>
              {children}
              <Toaster />
            </WorkflowProvider>
          </ThemeProvider>
        </React.StrictMode>
      </body>
    </html>
  );
}